#!/usr/bin/env bash

set -e

if [ -z `git branch | grep deployed` ]; then
  git checkout -b deployed
fi

./post

git config user.email "markville.compsci@gmail.com"
git config user.name "MSS CSEC"

git add -fA
git commit --allow-empty -m "$(git log -1 --pretty=%B) [deploy]"
git push origin deployed && echo "Deploy successful"

git checkout -
